# Generated by Django 3.2.19 on 2023-06-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230619_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='schedule_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='schedule_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
